# Namespace level Resource Quota allocation - dev
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
  labels:
    name: dev-quota
spec:
  hard:
    cpu: "1"
    memory: 3Gi
    pods: "5"
    replicationcontrollers: "20"
    resourcequotas: "1"
    services: "5"

---

# Namespace level Resource Quota allocation - prod
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: prod
  labels:
    name: prod-quota
spec:
  hard:
    cpu: "1"
    memory: 5Gi
    pods: "20"
    replicationcontrollers: "30"
    resourcequotas: "1"
    services: "10"